FROM debian:buster

RUN apt-get update && apt-get install -y mariadb-server mariadb-client

EXPOSE 3306

ENV MYSQL_ROOT_PASSWORD=root

COPY data/50-server.cnf /etc/mysql/mariadb.conf.d/

CMD ["/bin/bash"]
